# keep it lowercase only to avoid additional problems

[licenses]
authorized = [
  "apache",
  "apache 2.0",
  "apache software",
  "apache software license",
  "bsd",
  "bsd license",
  "new bsd",
  "new bds license",
  "3-clause bsd",
  "freeware",
  "gnu lesser general public license v2 (lgplv2)",
  "gnu lesser general public license v3 or later (lgplv3+)",
  "gnu lgpl",
  "gnu library or lesser general public license (lgpl)",
  "historical permission notice and disclaimer (hpnd)",
  "hpnd",
  "isc license",
  "isc license (iscl)",
  "lgpl with exceptions or zpl",
  "mit",
  "the mit license",
  "mit license",
  "mozilla public license 2.0 (mpl 2.0)",
  "public domain",
  "python software foundation",
  "python software foundation license",
  "simplified bsd",
  "zpl 2.1"]

unknown = ["unknown", "unknown license", "license", "license.txt"]

unauthorized = ["none"]

